{{- if .Values.pdb.enabled }}
{{- if not (or (eq .Values.workloadType "CronJob") (eq .Values.workloadType "Job")) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
{{ include "helm-blueprint.metadata" (dict "context" $ "extraAnnotations" .Values.pdb.annotations "extraLabels" .Values.pdb.labels "syncWaveDefault" "0") }}
spec:
  {{- with .Values.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.pdb.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-blueprint.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
