{{- range $name, $role := .Values.rbac.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
{{ include "helm-blueprint.metadata" (dict "name" (printf "%s-%s" (include "helm-blueprint.fullname" $) $name) "context" $ "extraAnnotations" $role.annotations "extraLabels" $role.labels "clusterScoped" true "syncWaveDefault" "-3" "syncWave" $role.syncWave) }}
rules:
  {{- toYaml $role.rules | nindent 2 }}
{{- end }}
