{{- $sa := default (dict) (default (dict) .Values.rbac).serviceAccount -}}
{{- if not (hasKey $sa "create") | ternary true $sa.create }}
apiVersion: v1
kind: ServiceAccount
{{ include "helm-blueprint.metadata" (dict "name" (include "helm-blueprint.rbac.serviceAccountName" .) "context" $ "extraAnnotations" .Values.rbac.serviceAccount.annotations "extraLabels" .Values.rbac.serviceAccount.labels "syncWaveDefault" "-3") }}
{{- if not (kindIs "invalid" .Values.rbac.serviceAccount.automountServiceAccountToken) }}
automountServiceAccountToken: {{ .Values.rbac.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- with .Values.rbac.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
