{{- range $name, $config := .Values.config.secrets }}
{{- if $config }}
{{- $annotations := default (dict) $config.annotations }}
{{- if $config.retain }}{{ $annotations = merge (dict "helm.sh/resource-policy" "keep") $annotations }}{{ end }}
---
apiVersion: v1
kind: Secret
{{ include "helm-blueprint.metadata" (dict "name" (printf "%s-%s" (include "helm-blueprint.fullname" $) $name) "context" $ "extraAnnotations" $annotations "extraLabels" $config.labels "syncWaveDefault" "-5" "syncWave" $config.syncWave) }}
type: {{ default "Opaque" $config.type }}
{{- with $config.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with $config.stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
