workloadType: Rollout
containers:
  app:
    image:
      repository: nginx
      tag: "1.27"
    ports:
      http:
        port: 80
    healthChecks:
      readiness:
        httpGet:
          path: /
          port: http
networking:
  services:
    stable:
      type: ClusterIP
      ports:
        http:
          port: 80
          containerPort: http
    canary:
      type: ClusterIP
      ports:
        http:
          port: 80
          containerPort: http
workloads:
  rollout:
    replicaCount: 1
    strategy:
      canary:
        steps:
          - setWeight: 50
          - pause: { duration: 5s }
