{{- if and (eq .Values.workloadType "Job") (not .Values.autoscaling.keda.enabled) }}
apiVersion: batch/v1
kind: Job
{{ include "helm-blueprint.metadata" (dict "context" $ "workload" true "syncWaveDefault" "0") }}
spec:
  {{- include "helm-blueprint.workloads.jobSpec" . | nindent 2 }}
  {{- if not (kindIs "invalid" .Values.workloads.job.suspend) }}
  suspend: {{ .Values.workloads.job.suspend }}
  {{- end }}
  template:
    {{- include "helm-blueprint.podTemplate" . | nindent 4 }}
{{- end }}
