workloadType: StatefulSet

containers:
  postgres:
    image:
      repository: postgres
      tag: "16"
    ports:
      postgres:
        port: 5432
    env:
      POSTGRES_DB:
        value: "mydb"
      POSTGRES_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: password
            external: true
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    mounts:
      - path: /var/lib/postgresql/data
        persistence: data

networking:
  services:
    postgres:
      type: ClusterIP
      ports:
        postgres:
          port: 5432

workloads:
  statefulSet:
    replicaCount: 3
    publishNotReadyAddresses: true
    podManagementPolicy: OrderedReady
    updateStrategy:
      type: RollingUpdate
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain

persistence:
  data:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 20Gi

pdb:
  enabled: true
  maxUnavailable: 1
